FROM node:18-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --production
COPY . .
EXPOSE 3000
ENV NODE_ENV=production
COPY scripts/waitForPrimary.js ./scripts/waitForPrimary.js
CMD ["sh", "-c", "node scripts/waitForPrimary.js && node src/index.js"]
